###
GET http://localhost:8080/api/stats/dashboard
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInVzZXItaWQiOiI5ZjI1MWU5Yy00MTk4LTQ1YzYtYmU4Yy1hYmU5OTQ1MjczZDgiLCJzdWIiOiJjZGlhekBleGFtcGxlLmNvbSIsImlhdCI6MTc3MDg2MzM5NywiZXhwIjoxNzcwOTQ5Nzk3fQ.cGarLr7GkCvEVZxo50NGxlEPzbboSf7_4xKj8o-h7gjYE3lTpKmI2IuQvZD3dalf
