name: "Backend CI: Spring boot & Java 21"

on:
  push: 
    branches: 
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: "Configurar JDK 21"
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: "Dar permisos de ejecuccion al gradlew"
        run: chmod +x ./gradlew

      - name: "Gradle Build"
        run: ./gradlew build --no-daemon -x test

      - name: "Obtener la version del proyecto"
        id: get_version
        run: echo "VERSION=$(./gradlew properties | grep ^'version:' | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: "Guardar el JAR"
        uses: actions/upload-artifact@v6
        with:
          name: backend-binary
          path: build/libs/*.jar

  publish-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: "Descargar el JAR"
        uses: actions/download-artifact@v6
        with:
          name: backend-binary
          path: ./release-assets

      - name: "Crear el release de Github"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build-and-test.outputs.version }}-${{ github.run_number }}
          name: Release v${{ needs.build-and-test.outputs.version }}
          files: ./release-assets/*.jar
          body: |
            ## Automated Release
            - Commit: ${{ github.sha }}
            - Status: Verified by CI
            - Environment: Java 21 / Spring Boot
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

